// !!! This is a file automatically generated by hipify!!!
#pragma once

#include <ATen/hip/HIPContextLight.h>

// Preserved for BC, as many files depend on these includes
#include <ATen/Context.h>
#include <ATen/hip/impl/HIPStreamMasqueradingAsCUDA.h>
#include <c10/util/Logging.h>
#include <ATen/hip/Exceptions.h>
