// !!! This is a file automatically generated by hipify!!!
#pragma once

#include <c10/core/Allocator.h>
#include <ATen/hip/CachingHostAllocator.h>

namespace at::cuda {

inline TORCH_CUDA_CPP_API at::Allocator* getPinnedMemoryAllocator() {
  return getCachingHostAllocator();
}
} // namespace at::cuda
